"""Column layout of the engine outputs published to the ``xray`` schema.

Generated from the engine parquet schemas: (column, sql type, parquet column, struct field).
Flat structs become one column per field; nested values are stored as JSONB.
"""

Column = tuple[str, str, str, str | None]

PANEL_TABLE = "entity_month_panel"
PANEL_COLUMNS: tuple[Column, ...] = (
    ('entity_kind', 'text', 'entity_kind', None),
    ('entity_id', 'text', 'entity_id', None),
    ('group_id', 'text', 'group_id', None),
    ('month', 'date', 'month', None),
    ('months_observed', 'bigint', 'months_observed', None),
    ('n_members', 'bigint', 'n_members', None),
    ('n_products', 'bigint', 'n_products', None),
    ('perimeter_changed', 'boolean', 'perimeter_changed', None),
    ('members_joined', 'bigint', 'members_joined', None),
    ('products_connected', 'bigint', 'products_connected', None),
    ('months_since_perimeter_change', 'bigint', 'months_since_perimeter_change', None),
    ('new_perimeter_inflow_share_3m', 'float', 'new_perimeter_inflow_share_3m', None),
    ('size_band', 'text', 'size_band', None),
    ('rows_month', 'bigint', 'rows_month', None),
    ('rows_3m', 'bigint', 'rows_3m', None),
    ('rows_base_median', 'float', 'rows_base_median', None),
    ('rows_base_months', 'bigint', 'rows_base_months', None),
    ('zero_row_month', 'boolean', 'zero_row_month', None),
    ('cash_month_end', 'float', 'cash_month_end', None),
    ('cash_intra_month_min', 'float', 'cash_intra_month_min', None),
    ('headroom', 'float', 'headroom', None),
    ('headroom_at_min', 'float', 'headroom_at_min', None),
    ('granted', 'float', 'granted', None),
    ('drawn', 'float', 'drawn', None),
    ('n_cash_products', 'bigint', 'n_cash_products', None),
    ('n_credit_lines', 'bigint', 'n_credit_lines', None),
    ('neg_liquidity_months_6m', 'bigint', 'neg_liquidity_months_6m', None),
    ('no_cash_anchor_share', 'float', 'no_cash_anchor_share', None),
    ('limit_assumed_constant', 'boolean', 'limit_assumed_constant', None),
    ('swept_subsidiary', 'boolean', 'swept_subsidiary', None),
    ('cash_share_of_group', 'float', 'cash_share_of_group', None),
    ('zero_balance_account_share', 'float', 'zero_balance_account_share', None),
    ('sweep_pairs_12m', 'bigint', 'sweep_pairs_12m', None),
    ('sentinel_balances_dropped', 'bigint', 'sentinel_balances_dropped', None),
    ('op_inflow_1m', 'float', 'op_inflow_1m', None),
    ('op_outflow_1m', 'float', 'op_outflow_1m', None),
    ('debt_service_1m', 'float', 'debt_service_1m', None),
    ('outflow_median_3m', 'float', 'outflow_median_3m', None),
    ('outflow_median_12m', 'float', 'outflow_median_12m', None),
    ('op_in_sum_6m_w', 'float', 'op_in_sum_6m_w', None),
    ('outflow_sum_6m_w', 'float', 'outflow_sum_6m_w', None),
    ('months_in_6m_window', 'bigint', 'months_in_6m_window', None),
    ('op_in_sum_12m_w', 'float', 'op_in_sum_12m_w', None),
    ('debt_service_sum_12m_w', 'float', 'debt_service_sum_12m_w', None),
    ('months_in_12m_window', 'bigint', 'months_in_12m_window', None),
    ('op_in_lfl_recent_mean', 'float', 'op_in_lfl_recent_mean', None),
    ('op_in_lfl_prior_mean', 'float', 'op_in_lfl_prior_mean', None),
    ('lfl_prior_months', 'bigint', 'lfl_prior_months', None),
    ('no_external_revenue', 'boolean', 'no_external_revenue', None),
    ('intragroup_in', 'float', 'intragroup_in', None),
    ('intragroup_out', 'float', 'intragroup_out', None),
    ('mirror_netted_1m', 'float', 'mirror_netted_1m', None),
    ('has_debt_products', 'boolean', 'has_debt_products', None),
    ('has_invoices', 'boolean', 'has_invoices', None),
    ('ap_n', 'bigint', 'ap_n', None),
    ('ap_neff', 'float', 'ap_neff', None),
    ('ap_amount', 'float', 'ap_amount', None),
    ('ap_days_beyond_terms', 'float', 'ap_days_beyond_terms', None),
    ('ap_stamped_share', 'float', 'ap_stamped_share', None),
    ('ap_open_share', 'float', 'ap_open_share', None),
    ('ap_open', 'float', 'ap_open', None),
    ('ap_overdue', 'float', 'ap_overdue', None),
    ('ap_aged_n', 'bigint', 'ap_aged_n', None),
    ('ap_aged_open_n', 'bigint', 'ap_aged_open_n', None),
    ('ar_n', 'bigint', 'ar_n', None),
    ('ar_neff', 'float', 'ar_neff', None),
    ('ar_amount', 'float', 'ar_amount', None),
    ('ar_days_beyond_terms', 'float', 'ar_days_beyond_terms', None),
    ('ar_stamped_share', 'float', 'ar_stamped_share', None),
    ('ar_open_share', 'float', 'ar_open_share', None),
    ('ar_open', 'float', 'ar_open', None),
    ('ar_overdue', 'float', 'ar_overdue', None),
    ('ar_aged_n', 'bigint', 'ar_aged_n', None),
    ('ar_aged_open_n', 'bigint', 'ar_aged_open_n', None),
    ('dash_share', 'float', 'dash_share', None),
    ('fx_excluded_share', 'float', 'fx_excluded_share', None),
    ('orphan_product_share', 'float', 'orphan_product_share', None),
)

SCORES_TABLE = "entity_month_score"
SCORES_COLUMNS: tuple[Column, ...] = (
    ('entity_kind', 'text', 'entity_kind', None),
    ('entity_id', 'text', 'entity_id', None),
    ('group_id', 'text', 'group_id', None),
    ('month', 'date', 'month', None),
    ('score', 'float', 'score', None),
    ('band', 'text', 'band', None),
    ('size_band', 'text', 'size_band', None),
    ('level', 'float', 'level', None),
    ('base', 'float', 'base', None),
    ('pillars_liquidity', 'float', 'pillars', 'liquidity'),
    ('pillars_payments', 'float', 'pillars', 'payments'),
    ('pillars_collections', 'float', 'pillars', 'collections'),
    ('pillars_activity', 'float', 'pillars', 'activity'),
    ('pillars_debt', 'float', 'pillars', 'debt'),
    ('weights_effective_liquidity', 'float', 'weights_effective', 'liquidity'),
    ('weights_effective_payments', 'float', 'weights_effective', 'payments'),
    ('weights_effective_collections', 'float', 'weights_effective', 'collections'),
    ('weights_effective_activity', 'float', 'weights_effective', 'activity'),
    ('weights_effective_debt', 'float', 'weights_effective', 'debt'),
    ('contributions_liquidity', 'float', 'contributions', 'liquidity'),
    ('contributions_payments', 'float', 'contributions', 'payments'),
    ('contributions_collections', 'float', 'contributions', 'collections'),
    ('contributions_activity', 'float', 'contributions', 'activity'),
    ('contributions_debt', 'float', 'contributions', 'debt'),
    ('penalty', 'float', 'penalty', None),
    ('cap_adjustment', 'float', 'cap_adjustment', None),
    ('caps_fired', 'jsonb', 'caps_fired', None),
    ('branch', 'text', 'branch', None),
    ('feed_live', 'boolean', 'feed_live', None),
    ('carried_from', 'date', 'carried_from', None),
    ('confidence', 'float', 'confidence', None),
    ('confidence_label', 'text', 'confidence_label', None),
    ('confidence_parts_history', 'float', 'confidence_parts', 'history'),
    ('confidence_parts_coverage', 'float', 'confidence_parts', 'coverage'),
    ('confidence_parts_quality', 'float', 'confidence_parts', 'quality'),
    ('delta', 'float', 'delta', None),
    ('delta_parts', 'jsonb', 'delta_parts', None),
    ('trend', 'text', 'trend', None),
    ('persistence_months', 'bigint', 'persistence_months', None),
    ('detected_since', 'date', 'detected_since', None),
    ('trajectory', 'jsonb', 'trajectory', None),
    ('gates', 'jsonb', 'gates', None),
    ('flags', 'jsonb', 'flags', None),
    ('abstained', 'boolean', 'abstained', None),
    ('abstain_reason', 'text', 'abstain_reason', None),
    ('unlock_hint', 'text', 'unlock_hint', None),
    ('months_observed', 'bigint', 'months_observed', None),
    ('perimeter_changed', 'boolean', 'perimeter_changed', None),
    ('drivers', 'jsonb', 'drivers', None),
    ('series_cash_month_end', 'float', 'series', 'cash_month_end'),
    ('series_cash_intra_month_min', 'float', 'series', 'cash_intra_month_min'),
    ('series_headroom', 'float', 'series', 'headroom'),
    ('series_drawn', 'float', 'series', 'drawn'),
    ('series_op_inflow_1m', 'float', 'series', 'op_inflow_1m'),
    ('series_op_outflow_1m', 'float', 'series', 'op_outflow_1m'),
    ('series_debt_service_1m', 'float', 'series', 'debt_service_1m'),
    ('series_buffer_days', 'float', 'series', 'buffer_days'),
    ('series_ap_days_beyond_terms', 'float', 'series', 'ap_days_beyond_terms'),
    ('series_ar_days_beyond_terms', 'float', 'series', 'ar_days_beyond_terms'),
    ('series_activity_coverage', 'float', 'series', 'activity_coverage'),
    ('series_activity_momentum', 'float', 'series', 'activity_momentum'),
    ('series_debt_burden', 'float', 'series', 'debt_burden'),
    ('observed_score', 'float', 'observed_score', None),
    ('predicted_future_score', 'float', 'predicted_future_score', None),
    ('forecast_delta', 'float', 'forecast_delta', None),
    ('shap_base_value', 'float', 'shap_base_value', None),
    ('explanation_residual', 'float', 'explanation_residual', None),
    ('feature_version', 'text', 'feature_version', None),
    ('model_version', 'text', 'model_version', None),
    ('engine_version', 'text', 'engine_version', None),
    ('params_hash', 'text', 'params_hash', None),
    ('dataset_hash', 'text', 'dataset_hash', None),
)

ALERTS_TABLE = "alert"
ALERTS_COLUMNS: tuple[Column, ...] = (
    ('id', 'text', 'id', None),
    ('entity_kind', 'text', 'entity_kind', None),
    ('entity_id', 'text', 'entity_id', None),
    ('group_id', 'text', 'group_id', None),
    ('month', 'date', 'month', None),
    ('kind', 'text', 'kind', None),
    ('state', 'text', 'state', None),
    ('title', 'text', 'title', None),
    ('detail', 'text', 'detail', None),
    ('suppressed_by_reason', 'text', 'suppressed_by', 'reason'),
    ('suppressed_by_since', 'date', 'suppressed_by', 'since'),
    ('suppressed_by_until', 'date', 'suppressed_by', 'until'),
)
